### ISSUE TITLE
TypeError: list indices must be integers or slices, not NoneType

### ISSUE THREAD

**Issue by nitishsharma14** [iamkroot/ilc-scraper#20] opened 2020-04-15 11:57 UTC
![Screenshot (42)](https://user-images.githubusercontent.com/63720511/79334376-cdc20a80-7f3d-11ea-9046-68d2c21646ce.png)

![Screenshot (43)](https://user-images.githubusercontent.com/63720511/79334661-52148d80-7f3e-11ea-85e9-7445458a8f41.png)

unable to download any lecture 
Windows OS
used both exe file and using command prompt/windows powershell ways.
Both methods are giving same type of error.

Course URL:- http://a.impartus.com/ilc/#/course/177457/805

**Comment by krashnat922** [comment] 2020-04-17 20:56
I am also having the same issue as.....

**list indices must be integers or slices, not NoneType**


Couldn't find C:\Users\KT\Downloads\Programs\imp_config.json. Will skip for now.
Saving to "C:\Users\KT\Downloads\Video\Impartus\PG-DITISS 2020"
Downloading lecture numbers: 8 9 10
Traceback (most recent call last):
  File "ilc_scrape.py", line 345, in <module>
  File "ilc_scrape.py", line 335, in main
  File "multiprocessing\pool.py", line 276, in starmap
  File "multiprocessing\pool.py", line 657, in get
  File "multiprocessing\pool.py", line 121, in worker
  File "multiprocessing\pool.py", line 47, in starmapstar
  File "downloader.py", line 167, in download_stream
  File "downloader.py", line 104, in get_angle_playlists
TypeError: list indices must be integers or slices, not NoneType
Processing 08. OS-Windows 2020-04-15.mkv
Processing 09. OS-Windows 2020-04-16.mkv
Processing 10. OS-Windows 2020-04-16.mkv
<class 'TypeError'> list indices must be integers or slices, not NoneType <traceback object at 0x0000022A08993E48>

**Comment by iamkroot** [comment] 2020-04-18 03:11
Dupe of #19

**Closed by iamkroot** 2020-04-18 03:11 UTC

**Comment by krashnat922** [comment] 2020-04-18 05:30
Please check once if this link shows videos to you and if you can solve this issue or guide us to solve this....!!!



[https://a.impartus.com/ilc/#/course/177459/805](https://a.impartus.com/ilc/#/course/177459/805)


If you got the issue please let me know what can i do to solve this issue...

**Comment by iamkroot** [comment] 2020-04-18 13:22
I can't access that one either.

@krashnat922 Please direct further discussion to #19
