### ISSUE TITLE
[BUG] [Couldnt download]

### ISSUE THREAD

**Issue by sundrb** [iamkroot/ilc-scraper#22] opened 2020-04-22 06:41 UTC
**Context**
* OS: [Windows 10 Enterprise 1809]
* Install method: [Executable]
* Your location: [Outside campus]
* Course URL: [https://a.impartus.com/ilc/#/course/142838/706
 (see [README](https://github.com/iamkroot/ilc-scraper#fixing-url-unrecognized-errors))]
* Lecture range: [1]

**Additional context**

**Describe the bug**

**Screenshots**

**Program output**
<details>
<summary>Click to see output</summary>
<p>

```
aving to "C:\Users\sundarb\OneDrive - Henkel\Desktop\Marketing (Merged - BAZC411\MBAZC411) (S2-19) 2019-20 Sem 2"
Downloading lecture numbers: 1
Traceback (most recent call last):
  File "ilc_scrape.py", line 345, in <module>
  File "ilc_scrape.py", line 335, in main
  File "multiprocessing\pool.py", line 276, in starmap
  File "multiprocessing\pool.py", line 657, in get
  File "multiprocessing\pool.py", line 121, in worker
  File "multiprocessing\pool.py", line 47, in starmapstar
  File "downloader.py", line 166, in download_stream
  File "downloader.py", line 104, in get_angle_playlists
TypeError: list indices must be integers or slices, not NoneType
Processing 01. Marketing Introduction 2020-01-11.mkv
<class 'TypeError'> list indices must be integers or slices, not NoneType <traceback object at 0x0000023A56C7A6C8>

```
</p>
</details>

**Comment by iamkroot** [comment] 2020-04-22 06:47
Dupe of #19. Please don't create duplicate issues. Direct all discussion to #19.

**Closed** 2020-04-22 06:46 UTC
